# Generated by Django 5.2.15 on 2026-07-05 18:11

import django.db.models.deletion
import justavalia.pedidos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=justavalia.pedidos.models._gerar_numero, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('AWAITING_PAYMENT', 'Aguardando pagamento'), ('AWAITING_UPLOAD', 'Aguardando envio'), ('PROCESSING', 'Processando'), ('PENDENCY', 'Pendência'), ('IN_TRIAGE', 'Em triagem'), ('DRAFTING', 'Gerando rascunho'), ('IN_REVIEW', 'Em revisão'), ('APPROVED_FOR_SIGNATURE', 'Aprovado para assinatura'), ('SIGNED', 'Assinado'), ('DELIVERED', 'Entregue'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=32)),
                ('cliente_nome', models.CharField(max_length=160)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('cliente_whatsapp', models.CharField(blank=True, max_length=32)),
                ('endereco_imovel', models.CharField(max_length=255)),
                ('tipo_imovel', models.CharField(default='residencial_urbano', max_length=40)),
                ('preco_centavos', models.PositiveIntegerField(default=29900)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TransicaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('AWAITING_PAYMENT', 'Aguardando pagamento'), ('AWAITING_UPLOAD', 'Aguardando envio'), ('PROCESSING', 'Processando'), ('PENDENCY', 'Pendência'), ('IN_TRIAGE', 'Em triagem'), ('DRAFTING', 'Gerando rascunho'), ('IN_REVIEW', 'Em revisão'), ('APPROVED_FOR_SIGNATURE', 'Aprovado para assinatura'), ('SIGNED', 'Assinado'), ('DELIVERED', 'Entregue'), ('CANCELLED', 'Cancelado')], max_length=32)),
                ('para_status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('AWAITING_PAYMENT', 'Aguardando pagamento'), ('AWAITING_UPLOAD', 'Aguardando envio'), ('PROCESSING', 'Processando'), ('PENDENCY', 'Pendência'), ('IN_TRIAGE', 'Em triagem'), ('DRAFTING', 'Gerando rascunho'), ('IN_REVIEW', 'Em revisão'), ('APPROVED_FOR_SIGNATURE', 'Aprovado para assinatura'), ('SIGNED', 'Assinado'), ('DELIVERED', 'Entregue'), ('CANCELLED', 'Cancelado')], max_length=32)),
                ('ator_desc', models.CharField(default='sistema', max_length=160)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transicoes_pedido', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicoes', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'transição',
                'verbose_name_plural': 'transições',
                'ordering': ['criado_em', 'id'],
            },
        ),
    ]
