# Generated by Django 5.2.15 on 2026-07-05 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidiaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('foto_fachada', 'Foto — fachada'), ('foto_ambiente', 'Foto — ambiente'), ('foto_detalhe', 'Foto — detalhe'), ('video_vistoria', 'Vídeo — vistoria'), ('doc_matricula', 'Documento — matrícula'), ('doc_iptu', 'Documento — IPTU'), ('doc_complementar', 'Documento — complementar')], max_length=24)),
                ('s3_key', models.CharField(max_length=512, unique=True)),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('tamanho_bytes', models.BigIntegerField(default=0)),
                ('etag', models.CharField(blank=True, max_length=128)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('upload_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('em_andamento', 'Upload em andamento'), ('recebido', 'Recebido'), ('erro', 'Erro')], default='em_andamento', max_length=16)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('recebido_em', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'mídia',
                'verbose_name_plural': 'mídias',
                'ordering': ['criado_em', 'id'],
            },
        ),
    ]
